#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 20 16:11:29 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Switch_MultistadioTB_behav -key {Behavioral:sim_1:Functional:Switch_MultistadioTB} -tclbatch Switch_MultistadioTB.tcl -view /home/giuseppericcio/Switch_Multistadio/Switch_Multistadio.srcs/sim_1/imports/Switch_Multistadio/Switch_MultistadioTB_behav.wcfg -log simulate.log"
xsim Switch_MultistadioTB_behav -key {Behavioral:sim_1:Functional:Switch_MultistadioTB} -tclbatch Switch_MultistadioTB.tcl -view /home/giuseppericcio/Switch_Multistadio/Switch_Multistadio.srcs/sim_1/imports/Switch_Multistadio/Switch_MultistadioTB_behav.wcfg -log simulate.log

