#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 27 17:25:55 CEST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Riconoscitore_Mealy_2_Modi_01_TB_behav -key {Behavioral:sim_1:Functional:Riconoscitore_Mealy_2_Modi_01_TB} -tclbatch Riconoscitore_Mealy_2_Modi_01_TB.tcl -view /home/giuseppericcio/Documenti/ASD/Riconoscitore_2_Modi/Riconoscitore_Mealy_2_Modi_01_TB_behav.wcfg -log simulate.log"
xsim Riconoscitore_Mealy_2_Modi_01_TB_behav -key {Behavioral:sim_1:Functional:Riconoscitore_Mealy_2_Modi_01_TB} -tclbatch Riconoscitore_Mealy_2_Modi_01_TB.tcl -view /home/giuseppericcio/Documenti/ASD/Riconoscitore_2_Modi/Riconoscitore_Mealy_2_Modi_01_TB_behav.wcfg -log simulate.log

