#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jan 20 16:11:26 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0b69eee36b104cc3acb2e3ae9bf560f3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Switch_MultistadioTB_behav xil_defaultlib.Switch_MultistadioTB -log elaborate.log"
xelab -wto 0b69eee36b104cc3acb2e3ae9bf560f3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Switch_MultistadioTB_behav xil_defaultlib.Switch_MultistadioTB -log elaborate.log

