#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 07 17:41:02 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_handshaking_A_B_behav -key {Behavioral:sim_1:Functional:tb_handshaking_A_B} -tclbatch tb_handshaking_A_B.tcl -view /home/giuseppericcio/Documenti/ASD/Progetti tesina/Handshaking_v3/Handshaking_v3.srcs/sim_1/imports/Handshaking_v3/tb_handshaking_A_B_behav.wcfg -log simulate.log"
xsim tb_handshaking_A_B_behav -key {Behavioral:sim_1:Functional:tb_handshaking_A_B} -tclbatch tb_handshaking_A_B.tcl -view /home/giuseppericcio/Documenti/ASD/Progetti tesina/Handshaking_v3/Handshaking_v3.srcs/sim_1/imports/Handshaking_v3/tb_handshaking_A_B_behav.wcfg -log simulate.log

