@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Feb 20 17:52:36 +0100 2022
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_handshaking_A_B_behav -key {Behavioral:sim_1:Functional:tb_handshaking_A_B} -tclbatch tb_handshaking_A_B.tcl -view C:/Users/digig/OneDrive - Università di Napoli Federico II/Desktop/ARC/ProgettoASD_2021-22-main/Esercizio 7/Handshaking/Handshaking/Handshaking.srcs/sim_1/imports/Handshaking_v3/tb_handshaking_A_B_behav.wcfg -log simulate.log"
call xsim  tb_handshaking_A_B_behav -key {Behavioral:sim_1:Functional:tb_handshaking_A_B} -tclbatch tb_handshaking_A_B.tcl -view C:/Users/digig/OneDrive - Università di Napoli Federico II/Desktop/ARC/ProgettoASD_2021-22-main/Esercizio 7/Handshaking/Handshaking/Handshaking.srcs/sim_1/imports/Handshaking_v3/tb_handshaking_A_B_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
