#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 10 15:57:24 CET 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0cf88964be694c86a2adc82de856d045 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rete_16_4_TB_behav xil_defaultlib.rete_16_4_TB -log elaborate.log"
xelab -wto 0cf88964be694c86a2adc82de856d045 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rete_16_4_TB_behav xil_defaultlib.rete_16_4_TB -log elaborate.log

