#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 28 11:34:10 CET 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim system_tb_behav -key {Behavioral:sim_1:Functional:system_tb} -tclbatch system_tb.tcl -view /home/giuseppericcio/Documenti/ASD/Progetti tesina/Mic-1/Mic-1.srcs/sim_1/imports/giuseppericcio/Config.wcfg -log simulate.log"
xsim system_tb_behav -key {Behavioral:sim_1:Functional:system_tb} -tclbatch system_tb.tcl -view /home/giuseppericcio/Documenti/ASD/Progetti tesina/Mic-1/Mic-1.srcs/sim_1/imports/giuseppericcio/Config.wcfg -log simulate.log

