#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 17 12:08:19 CET 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b1cc13864efa43108b4ad263add05e55 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cronometroTB_behav xil_defaultlib.cronometroTB -log elaborate.log"
xelab -wto b1cc13864efa43108b4ad263add05e55 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cronometroTB_behav xil_defaultlib.cronometroTB -log elaborate.log

