#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 21 10:07:11 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3728fc74d0d44ee0983f847cec6d2171 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_Robertson_behav xil_defaultlib.tb_Robertson -log elaborate.log"
xelab -wto 3728fc74d0d44ee0983f847cec6d2171 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_Robertson_behav xil_defaultlib.tb_Robertson -log elaborate.log

