#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 21 10:07:15 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_Robertson_behav -key {Behavioral:sim_1:Functional:tb_Robertson} -tclbatch tb_Robertson.tcl -view /home/giuseppericcio/Documenti/Robertson_MULTIP/tb_Robertson_behav.wcfg -log simulate.log"
xsim tb_Robertson_behav -key {Behavioral:sim_1:Functional:tb_Robertson} -tclbatch tb_Robertson.tcl -view /home/giuseppericcio/Documenti/Robertson_MULTIP/tb_Robertson_behav.wcfg -log simulate.log

