@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Feb 19 12:48:42 +0100 2022
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Shift_Register_TB_behav -key {Behavioral:sim_1:Functional:Shift_Register_TB} -tclbatch Shift_Register_TB.tcl -view C:/Users/digig/OneDrive - Università di Napoli Federico II/Desktop/ARC/ProgettoASD_2021-22-main/Esercizio 4/Shift_Register_S/Shift_Register_S/Shift_Register_S.srcs/sim_1/imports/Shift_Register_S/Shift_Register_TB_behav.wcfg -log simulate.log"
call xsim  Shift_Register_TB_behav -key {Behavioral:sim_1:Functional:Shift_Register_TB} -tclbatch Shift_Register_TB.tcl -view C:/Users/digig/OneDrive - Università di Napoli Federico II/Desktop/ARC/ProgettoASD_2021-22-main/Esercizio 4/Shift_Register_S/Shift_Register_S/Shift_Register_S.srcs/sim_1/imports/Shift_Register_S/Shift_Register_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
